### ISSUE TITLE
cannot run more than one chrome webdriver at the same time

### ISSUE THREAD

**Issue by drx19** [Hari-Nagarajan/nvidia-bot#131]
hello, after updating to todays update, I am unable to run more than one selenium bot at once. 

for example:
I cannot run to evga bots or one evga bot and one amazon bot.

I get this error:
![image](https://user-images.githubusercontent.com/71615615/94199371-b5f49800-fe86-11ea-86f2-bff7fa01d4ae.png)

the issue was confirmed by another user as well. before updating, the issue was not there.

Thanks.

**Comment by Hari-Nagarajan** [comment]
Pull the latest version, I just tested 2x amazon and 2x evga.

**Comment by notpentadactyl** [comment]
I have the same issue with current version with 2x nvidia.

**Comment by Hari-Nagarajan** [comment]
No you dont because nvidia doesn't use chromedriver.

**Comment by notpentadactyl** [comment]
Yeah it seems to be a different issue, it sometimes happens but sometimes it does not.

**Comment by notpentadactyl** [comment]
```
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    cli.main()
  File "C:\Users\Foobar\.virtualenvs\nvidia-bot-W0ot2hU8\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Foobar\.virtualenvs\nvidia-bot-W0ot2hU8\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Foobar\.virtualenvs\nvidia-bot-W0ot2hU8\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Foobar\.virtualenvs\nvidia-bot-W0ot2hU8\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Foobar\.virtualenvs\nvidia-bot-W0ot2hU8\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Foobar\nvidia-bot\cli\cli.py", line 35, in nvidia
    nv.run_items()
  File "C:\Users\Foobar\nvidia-bot\stores\nvidia.py", line 236, in run_items
    log.debug(f"Future Result: {fut.result()}")
  File "c:\users\Foobar\appdata\local\programs\python\python38\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "c:\users\Foobar\appdata\local\programs\python\python38\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "c:\users\Foobar\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Foobar\nvidia-bot\stores\nvidia.py", line 249, in buy
    cart_success, cart_url = self.get_cart_url(product_id)
  File "C:\Users\Foobar\nvidia-bot\stores\nvidia.py", line 284, in get_cart_url
    success, token = self.get_session_token()
  File "C:\Users\Foobar\nvidia-bot\stores\nvidia.py", line 310, in get_session_token
    response_json = response.json()
  File "C:\Users\Foobar\.virtualenvs\nvidia-bot-W0ot2hU8\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "c:\users\Foobar\appdata\local\programs\python\python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "c:\users\Foobar\appdata\local\programs\python\python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\Foobar\appdata\local\programs\python\python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
