### ISSUE TITLE
crash -- ubuntu server shell since update

### ISSUE THREAD

**Issue by Costin-Nox** [Hari-Nagarajan/nvidia-bot#209]
(nvidia-bot) costin@freenas-ubuntu:~/nvidia-bot# python3 app.py nvidia --interval 15
INFO: "2020-10-01 18:13:49,724 - Initializing notification handlers
INFO: "2020-10-01 18:13:49,726 - Enabled Handlers: ['Audio', 'Twilio']
? What GPU are you after?  3080
? What locale shall we use?  en_us
ERROR: "2020-10-01 18:13:54,979 - No module named 'gi'
WARNING: "2020-10-01 18:13:54,979 - Error playing notification sound. Disabling local audio notifications.                                                  INFO: "2020-10-01 18:13:55,543 - SMS Sent: SMb419e7ac267642469f02d8d2949c3843                                                                               Traceback (most recent call last):
  File "app.py", line 5, in <module>
    cli.main()
  File "/home/costin/.local/share/virtualenvs/nvidia-bot-u-HkRj3L/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/costin/.local/share/virtualenvs/nvidia-bot-u-HkRj3L/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/costin/.local/share/virtualenvs/nvidia-bot-u-HkRj3L/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/costin/.local/share/virtualenvs/nvidia-bot-u-HkRj3L/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/costin/.local/share/virtualenvs/nvidia-bot-u-HkRj3L/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/costin/nvidia-bot/cli/cli.py", line 20, in decorator
    func(*args, **kwargs)
  File "/home/costin/nvidia-bot/cli/cli.py", line 52, in nvidia
    nv = NvidiaBuyer(gpu, locale, test, interval)
  File "/home/costin/nvidia-bot/stores/nvidia.py", line 76, in __init__
    self.cj = browser_cookie3.load(".nvidia.com")
  File "/home/costin/.local/share/virtualenvs/nvidia-bot-u-HkRj3L/lib/python3.7/site-packages/browser_cookie3/__init__.py", line 484, in load
    for cookie in cookie_fn(domain_name=domain_name):
  File "/home/costin/.local/share/virtualenvs/nvidia-bot-u-HkRj3L/lib/python3.7/site-packages/browser_cookie3/__init__.py", line 467, in chrome                 return Chrome(cookie_file, domain_name, key_file).load()
  File "/home/costin/.local/share/virtualenvs/nvidia-bot-u-HkRj3L/lib/python3.7/site-packages/browser_cookie3/__init__.py", line 227, in __init__
    self.tmp_cookie_file = create_local_copy(cookie_file)
  File "/home/costin/.local/share/virtualenvs/nvidia-bot-u-HkRj3L/lib/python3.7/site-packages/browser_cookie3/__init__.py", line 45, in create_local_copy
    if os.path.exists(cookie_file):
  File "/usr/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by 0xz00n** [comment]
This appears to be fixed by navigating to the card page using Chromium (e.g. when using a fresh VM).  The cookie can't be loaded because it doesn't exist.  However, after fixing that bit, you run into a second error:

```
(nvidia-bot) [10:33:56]z00n@kalipso:~/Git/nvidia-bot$ python app.py nvidia --interval 15
INFO: "2020-10-02 10:36:24,947 - Initializing notification handlers
INFO: "2020-10-02 10:36:24,949 - Enabled Handlers: ['Audio']
? What GPU are you after?  3080
? What locale shall we use?  en_us
ERROR: "2020-10-02 10:36:27,323 - No module named 'gi'
WARNING: "2020-10-02 10:36:27,323 - Error playing notification sound. Disabling local audio notifications.
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    cli.main()
  File "/home/z00n/.local/share/virtualenvs/nvidia-bot-o392TV1K/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/z00n/.local/share/virtualenvs/nvidia-bot-o392TV1K/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/z00n/.local/share/virtualenvs/nvidia-bot-o392TV1K/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/z00n/.local/share/virtualenvs/nvidia-bot-o392TV1K/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/z00n/.local/share/virtualenvs/nvidia-bot-o392TV1K/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/z00n/Git/nvidia-bot/cli/cli.py", line 20, in decorator
    func(*args, **kwargs)
  File "/home/z00n/Git/nvidia-bot/cli/cli.py", line 52, in nvidia
    nv = NvidiaBuyer(gpu, locale, test, interval)
  File "/home/z00n/Git/nvidia-bot/stores/nvidia.py", line 76, in __init__
    self.cj = browser_cookie3.load(".nvidia.com")
  File "/home/z00n/.local/share/virtualenvs/nvidia-bot-o392TV1K/lib/python3.8/site-packages/browser_cookie3/__init__.py", line 484, in load
    for cookie in cookie_fn(domain_name=domain_name):
  File "/home/z00n/.local/share/virtualenvs/nvidia-bot-o392TV1K/lib/python3.8/site-packages/browser_cookie3/__init__.py", line 467, in chrome
    return Chrome(cookie_file, domain_name, key_file).load()
  File "/home/z00n/.local/share/virtualenvs/nvidia-bot-o392TV1K/lib/python3.8/site-packages/browser_cookie3/__init__.py", line 269, in load
    value = self._decrypt(item[5], item[6])
  File "/home/z00n/.local/share/virtualenvs/nvidia-bot-o392TV1K/lib/python3.8/site-packages/browser_cookie3/__init__.py", line 322, in _decrypt
    decrypted += cipher.feed()
  File "/home/z00n/.local/share/virtualenvs/nvidia-bot-o392TV1K/lib/python3.8/site-packages/pyaes/blockfeeder.py", line 169, in feed
    result = self._final(self._buffer, self._padding)
  File "/home/z00n/.local/share/virtualenvs/nvidia-bot-o392TV1K/lib/python3.8/site-packages/pyaes/blockfeeder.py", line 77, in _block_final_decrypt
    return strip_PKCS7_padding(self.decrypt(data))
  File "/home/z00n/.local/share/virtualenvs/nvidia-bot-o392TV1K/lib/python3.8/site-packages/pyaes/util.py", line 58, in strip_PKCS7_padding
    raise ValueError("invalid padding byte")
ValueError: invalid padding byte
```

I haven't had time to dig into this any further, though.  Best guess is that the cookie isn't being stripped properly before being passed to pyaes.

Also, @Costin-Nox , I suggest against git pulling latest.  You lack of the gi lib as indicated by the `No module named 'gi'` error that would otherwise be solved with a fresh install of the bot, or manually installing the missing library.  This is all assuming that you didn't intentionally leave that lib uninstalled.

**Comment by Costin-Nox** [comment]
> This appears to be fixed by navigating to the card page using Chromium (e.g. when using a fresh VM). The cookie can't be loaded because it doesn't exist. However, after fixing that bit, you run into a second error:
> 
> ```
> (nvidia-bot) [10:33:56]z00n@kalipso:~/Git/nvidia-bot$ python app.py nvidia --interval 15
> INFO: "2020-10-02 10:36:24,947 - Initializing notification handlers
> INFO: "2020-10-02 10:36:24,949 - Enabled Handlers: ['Audio']
> ? What GPU are you after?  3080
> ? What locale shall we use?  en_us
> ERROR: "2020-10-02 10:36:27,323 - No module named 'gi'
> WARNING: "2020-10-02 10:36:27,323 - Error playing notification sound. Disabling local audio notifications.
> Traceback (most recent call last):
>   File "app.py", line 5, in <module>
>     cli.main()
>   File "/home/z00n/.local/share/virtualenvs/nvidia-bot-o392TV1K/lib/python3.8/site-packages/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/z00n/.local/share/virtualenvs/nvidia-bot-o392TV1K/lib/python3.8/site-packages/click/core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "/home/z00n/.local/share/virtualenvs/nvidia-bot-o392TV1K/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/z00n/.local/share/virtualenvs/nvidia-bot-o392TV1K/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/z00n/.local/share/virtualenvs/nvidia-bot-o392TV1K/lib/python3.8/site-packages/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "/home/z00n/Git/nvidia-bot/cli/cli.py", line 20, in decorator
>     func(*args, **kwargs)
>   File "/home/z00n/Git/nvidia-bot/cli/cli.py", line 52, in nvidia
>     nv = NvidiaBuyer(gpu, locale, test, interval)
>   File "/home/z00n/Git/nvidia-bot/stores/nvidia.py", line 76, in __init__
>     self.cj = browser_cookie3.load(".nvidia.com")
>   File "/home/z00n/.local/share/virtualenvs/nvidia-bot-o392TV1K/lib/python3.8/site-packages/browser_cookie3/__init__.py", line 484, in load
>     for cookie in cookie_fn(domain_name=domain_name):
>   File "/home/z00n/.local/share/virtualenvs/nvidia-bot-o392TV1K/lib/python3.8/site-packages/browser_cookie3/__init__.py", line 467, in chrome
>     return Chrome(cookie_file, domain_name, key_file).load()
>   File "/home/z00n/.local/share/virtualenvs/nvidia-bot-o392TV1K/lib/python3.8/site-packages/browser_cookie3/__init__.py", line 269, in load
>     value = self._decrypt(item[5], item[6])
>   File "/home/z00n/.local/share/virtualenvs/nvidia-bot-o392TV1K/lib/python3.8/site-packages/browser_cookie3/__init__.py", line 322, in _decrypt
>     decrypted += cipher.feed()
>   File "/home/z00n/.local/share/virtualenvs/nvidia-bot-o392TV1K/lib/python3.8/site-packages/pyaes/blockfeeder.py", line 169, in feed
>     result = self._final(self._buffer, self._padding)
>   File "/home/z00n/.local/share/virtualenvs/nvidia-bot-o392TV1K/lib/python3.8/site-packages/pyaes/blockfeeder.py", line 77, in _block_final_decrypt
>     return strip_PKCS7_padding(self.decrypt(data))
>   File "/home/z00n/.local/share/virtualenvs/nvidia-bot-o392TV1K/lib/python3.8/site-packages/pyaes/util.py", line 58, in strip_PKCS7_padding
>     raise ValueError("invalid padding byte")
> ValueError: invalid padding byte
> ```
> 
> I haven't had time to dig into this any further, though. Best guess is that the cookie isn't being stripped properly before being passed to pyaes.
> 
> Also, @Costin-Nox , I suggest against git pulling latest. You lack of the gi lib as indicated by the `No module named 'gi'` error that would otherwise be solved with a fresh install of the bot, or manually installing the missing library. This is all assuming that you didn't intentionally leave that lib uninstalled.

Thanks for the reply, i dont deal with python, not super familiar at all with it. It's running on an ubuntu server, so no chrome or anything. This all runs fine on my mac, but i was hoping to let it run headless on my server. Is it getting the session from the cookie to do the checkout, maybe i can look at the code and just grab the data from the cookie off my desktop and feed it somewhere.

As far as pulling, i just do a git reset --hard origin/master and then pipenv install to update the dependencies. Seems to be the same idea as composer/node dependency file with a lock, so it should just fast forward to the latest lock file? Unless i'm totally wrong. 

I'll just run this on my mac and leave it on, seems easier! 

Cheers!

**Comment by awrel34** [comment]
I manage to make the nvidia one work on an Ubuntu vps
You have to use vnc ans xforwarding to launch chrome a first Time. This will create the needed folder tree under .local/config.

**Comment by Costin-Nox** [comment]
Yup, can confirm, set up x11 forwarding to WSL... installed chrome, ran it one and it works now. You must install chrome, i tried it with firefox and it did not work.
