### ISSUE TITLE
EVGA option not working

### ISSUE THREAD

**Issue by atanc** [Hari-Nagarajan/nvidia-bot#227]
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    cli.main()
  File "C:\Users\A\.virtualenvs\nvidia-bot-zSm52fms\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\A\.virtualenvs\nvidia-bot-zSm52fms\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\A\.virtualenvs\nvidia-bot-zSm52fms\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\A\.virtualenvs\nvidia-bot-zSm52fms\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\A\.virtualenvs\nvidia-bot-zSm52fms\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\A\Documents\GitHub\nvidia-bot\cli\cli.py", line 26, in decorator
    func(*args, **kwargs)
  File "C:\Users\A\Documents\GitHub\nvidia-bot\cli\cli.py", line 91, in evga
    ev = Evga(headless)
  File "C:\Users\A\Documents\GitHub\nvidia-bot\stores\evga.py", line 54, in __init__
    self.login(username, password)
UnboundLocalError: local variable 'username' referenced before assignment

Not sure what is going on, all my information regarding the login in correct.

**Comment by worst-mod-confirmed** [comment]
This is an issue with json file. The script can't parse the "username" key which is likely due to a improper formatting.

**Comment by atanc** [comment]
> This is an issue with json file. The script can't parse the "username" key which is likely due to a improper formatting.

How do I fix it? Use notepad to edit the json file or another way?
