### ISSUE TITLE
ERROR:browser_gpu_channel_host_factory.cc(167)] Failed to launch GPU process.

### ISSUE THREAD

**Issue by Charlweed** [Hari-Nagarajan/nvidia-bot#267]
This is my first attempt to run. I have python 39. I see the warning of dependency issues for 3.9.0, but I thought I had solved them. I will try to downgrade, and will update this issue if there is any change.

Behavior:
Chrome window opens, but is blank. The console shows the error:

```
DevTools listening on ws://127.0.0.1:52318/devtools/browser/7b9aee00-ce11-49cf-8d9c-af9d5e422307
[16156:14960:1029/133327.629:ERROR:browser_gpu_channel_host_factory.cc(167)] Failed to launch GPU process.
```

After a minute or so, the bot dings, the window closes, and a stack trace is printed on the console:
```
Traceback (most recent call last):
  File "C:\Users\rastro\projects\3rd_party\nvidia-bot\app.py", line 5, in <module>
    cli.main()
  File "C:\Users\rastro\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\rastro\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\rastro\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\rastro\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\rastro\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\rastro\projects\3rd_party\nvidia-bot\cli\cli.py", line 27, in decorator
    func(*args, **kwargs)
  File "C:\Users\rastro\projects\3rd_party\nvidia-bot\cli\cli.py", line 80, in amazon
    amzn_obj = Amazon(headless=headless, notification_handler=notification_handler)
  File "C:\Users\rastro\projects\3rd_party\nvidia-bot\stores\amazon.py", line 83, in __init__
    self.driver = webdriver.Chrome(executable_path=binary_path, options=options)
  File "C:\Users\rastro\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\rastro\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\rastro\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\rastro\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\rastro\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: unable to discover open pages
```

**Comment by Charlweed** [comment]
Confirming that I get the same error with Python 3.8.6

**Comment by Charlweed** [comment]
Confirming that I get the same error with Python 3.8.6:

```
[5008:6472:1029/175521.969:ERROR:browser_gpu_channel_host_factory.cc(167)] Failed to launch GPU process.

DevTools listening on ws://127.0.0.1:53235/devtools/browser/d01b94a7-b881-474e-a38c-53c1ef0d9195
[5008:6472:1029/175522.048:ERROR:browser_gpu_channel_host_factory.cc(167)] Failed to launch GPU process.
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    cli.main()
  File "C:\Users\rastro\AppData\Local\Programs\Python\Python38-32\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\rastro\AppData\Local\Programs\Python\Python38-32\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\rastro\AppData\Local\Programs\Python\Python38-32\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\rastro\AppData\Local\Programs\Python\Python38-32\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\rastro\AppData\Local\Programs\Python\Python38-32\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\rastro\projects\3rd_party\nvidia-bot\cli\cli.py", line 27, in decorator
    func(*args, **kwargs)
  File "C:\Users\rastro\projects\3rd_party\nvidia-bot\cli\cli.py", line 80, in amazon
    amzn_obj = Amazon(headless=headless, notification_handler=notification_handler)
  File "C:\Users\rastro\projects\3rd_party\nvidia-bot\stores\amazon.py", line 83, in __init__
    self.driver = webdriver.Chrome(executable_path=binary_path, options=options)
  File "C:\Users\rastro\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\rastro\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\rastro\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\rastro\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\rastro\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response

```
