### ISSUE TITLE
Nvidia login traceback?

### ISSUE THREAD

**Issue by sanjaysatoji** [Hari-Nagarajan/nvidia-bot#41]
`DevTools listening on ws://127.0.0.1:62031/devtools/browser/0241f930-8d8f-43a8-b449-d4778173ffff
INFO: "2020-09-21 09:25:36,874 - Signing in.
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    cli.main()
  File "C:\Users\Administrator\.conda\envs\nvidia2\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\.conda\envs\nvidia2\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\.conda\envs\nvidia2\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\.conda\envs\nvidia2\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\.conda\envs\nvidia2\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\nvidia-bot-master\cli\cli.py", line 30, in nvidia
    nv = NvidiaBuyer(gpu, locale)
  File "C:\Users\Administrator\Desktop\nvidia-bot-master\stores\nvidia.py", line 217, in __init__
    self.sign_in()
  File "C:\Users\Administrator\Desktop\nvidia-bot-master\stores\nvidia.py", line 516, in sign_in
    email.send_keys(self.nvidia_login)
AttributeError: 'NvidiaBuyer' object has no attribute 'nvidia_login'

C:\Users\Administrator\Desktop\nvidia-bot-master>[28208:29372:0921/092542.839:ERROR:device_event_log_impl.cc(208)] [09:25:42.839] Bluetooth: bluetooth_adapter_winrt.cc:1164 RequestRadioAccessAsync failed: RadioAccessStatus::DeniedByUserWill not be able to change radio power.`

I'm using the version that was posted 22 mins ago. Thank you for the help and great utility!

**Comment by sanjaysatoji** [comment]
The solution is to to rename autobuy_config.template_json to autobuy_config.json
