### ISSUE TITLE
Amazon Closes after a time.

### ISSUE THREAD

**Issue by SauceGodPluto** [Hari-Nagarajan/nvidia-bot#54]
![image](https://user-images.githubusercontent.com/54643230/93834358-9cb2d800-fc49-11ea-93a9-12d861a620f3.png)

**Comment by dagzyx** [comment]
I get a similar error, but using the nvidia command instead of the amazon one. It happens most often after the bot has been running for a little while.

----------------------------------------------------------------------------------------------------------------------------------------------

 ? What GPU are you after?  3080
? What locale shall we use?  en_us
INFO: "2020-09-21 20:28:35,145 - Initializing notification handlers
INFO: "2020-09-21 20:28:35,146 - Enabled Handlers: []
INFO: "2020-09-21 20:28:35,146 - Opening Webdriver

DevTools listening on ws://127.0.0.1:57334/devtools/browser/3959a053-9d50-42c7-99f5-f9d5985182fe

[11772:20488:0921/202838.205:ERROR:device_event_log_impl.cc(208)] [20:28:38.205] Bluetooth: bluetooth_adapter_winrt.cc:1074 Getting Default Adapter failed.

INFO: "2020-09-21 20:28:38,259 - Signing in.
INFO: "2020-09-21 20:28:40,438 - Adding driver cookies to session
INFO: "2020-09-21 20:28:40,438 - Getting product IDs
INFO: "2020-09-21 20:28:42,083 - We have 1 product IDs for NVIDIA GEFORCE RTX 3080
INFO: "2020-09-21 20:28:42,083 - Product IDs: {5438481700}
INFO: "2020-09-21 20:28:42,084 - Checking stock for 5438481700 at 3 second intervals.
Traceback (most recent call last):
  File "C:\Users\Matt\.virtualenvs\nvidia-bot-master-2BcfJBKM\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Matt\.virtualenvs\nvidia-bot-master-2BcfJBKM\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\Matt\.virtualenvs\nvidia-bot-master-2BcfJBKM\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "c:\users\matt\appdata\local\programs\python\python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "c:\users\matt\appdata\local\programs\python\python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "c:\users\matt\appdata\local\programs\python\python38\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "c:\users\matt\appdata\local\programs\python\python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "c:\users\matt\appdata\local\programs\python\python38\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "c:\users\matt\appdata\local\programs\python\python38\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matt\.virtualenvs\nvidia-bot-master-2BcfJBKM\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Matt\.virtualenvs\nvidia-bot-master-2BcfJBKM\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Users\Matt\.virtualenvs\nvidia-bot-master-2BcfJBKM\lib\site-packages\urllib3\util\retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Matt\.virtualenvs\nvidia-bot-master-2BcfJBKM\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Matt\.virtualenvs\nvidia-bot-master-2BcfJBKM\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Matt\.virtualenvs\nvidia-bot-master-2BcfJBKM\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\Matt\.virtualenvs\nvidia-bot-master-2BcfJBKM\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "c:\users\matt\appdata\local\programs\python\python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "c:\users\matt\appdata\local\programs\python\python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "c:\users\matt\appdata\local\programs\python\python38\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "c:\users\matt\appdata\local\programs\python\python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "c:\users\matt\appdata\local\programs\python\python38\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "c:\users\matt\appdata\local\programs\python\python38\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 5, in <module>
    cli.main()
  File "C:\Users\Matt\.virtualenvs\nvidia-bot-master-2BcfJBKM\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Matt\.virtualenvs\nvidia-bot-master-2BcfJBKM\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Matt\.virtualenvs\nvidia-bot-master-2BcfJBKM\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Matt\.virtualenvs\nvidia-bot-master-2BcfJBKM\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Matt\.virtualenvs\nvidia-bot-master-2BcfJBKM\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Matt\Desktop\nvidia-bot-master\cli\cli.py", line 31, in nvidia
    nv.run_items()
  File "C:\Users\Matt\Desktop\nvidia-bot-master\stores\nvidia.py", line 289, in run_items
    log.info(fut.result())
  File "c:\users\matt\appdata\local\programs\python\python38\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "c:\users\matt\appdata\local\programs\python\python38\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "c:\users\matt\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Matt\Desktop\nvidia-bot-master\stores\nvidia.py", line 298, in buy
    while not self.add_to_cart(product_id) and self.enabled:
  File "C:\Users\Matt\Desktop\nvidia-bot-master\stores\nvidia.py", line 400, in add_to_cart
    response = self.session.post(
  File "C:\Users\Matt\.virtualenvs\nvidia-bot-master-2BcfJBKM\lib\site-packages\requests\sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\Matt\.virtualenvs\nvidia-bot-master-2BcfJBKM\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Matt\.virtualenvs\nvidia-bot-master-2BcfJBKM\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Matt\.virtualenvs\nvidia-bot-master-2BcfJBKM\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))

----------------------------------------------------------------------------------------------------------------------------------------------

**Comment by camborambo** [comment]
I encountered this issue as well after running it for 3 hours. Will pull the latest and try again.
