### ISSUE TITLE
Bug: Timeout exception is not caught

### ISSUE THREAD

**Issue by jeremych1000** [Hari-Nagarajan/nvidia-bot#72]
Hello, running nvidia-bot and sometimes it crashes after a random period of time, instead of catching the exception and retrying in the next period. e.g. this following log came after around 20 minutes, but sometimes it can run overnight without problems.

Running on Mac.

```
❯ uname -a
Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64

❯ pip freeze
aiohttp==3.6.2
async-timeout==3.0.1
attrs==20.2.0
certifi==2020.6.20
chardet==3.0.4
chromedriver-py==85.0.4183.87
click==7.1.2
colorama==0.4.3
discord-webhook==0.9.0
furl==2.1.0
halo==0.0.30
idna==2.10
log-symbols==0.0.14
multidict==4.7.6
orderedmultidict==1.0.1
prompt-toolkit==3.0.7
pycryptodome==3.9.8
PyJWT==1.7.1
pytz==2020.1
questionary==1.5.2
requests==2.24.0
selenium==3.141.0
six==1.15.0
slackclient==2.9.0
spinlog==0.3.0
spinners==0.0.24
termcolor==1.1.0
twilio==6.45.2
typing-extensions==3.7.4.3
urllib3==1.25.10
wcwidth==0.2.5
yarl==1.5.1

❯ git rev-parse HEAD
b88b34d5e2368d9eb7980759df6807408eb120d8
```

Terminal log:
```
❯ python3 app.py nvidia
? What GPU are you after?  3080
? What locale shall we use?  en_gb
INFO: "2020-09-22 18:27:16,199 - Initializing notification handlers
INFO: "2020-09-22 18:27:16,200 - Enabled Handlers: []
INFO: "2020-09-22 18:27:16,200 - Opening Webdriver
INFO: "2020-09-22 18:27:18,369 - Signing in.
INFO: "2020-09-22 18:27:19,668 - Adding driver cookies to session
INFO: "2020-09-22 18:27:19,668 - Getting product IDs
INFO: "2020-09-22 18:27:20,956 - We have 1 product IDs for NVIDIA GEFORCE RTX 3080
INFO: "2020-09-22 18:27:20,957 - Product IDs: {5438792800}
INFO: "2020-09-22 18:27:20,957 - Checking stock for 5438792800 at 3 second intervals.
Traceback (most recent call last):
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 5, in <module>
    cli.main()
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/jeremychan/GitHub/nvidia-bot/cli/cli.py", line 32, in nvidia
    nv.run_items()
  File "/Users/jeremychan/GitHub/nvidia-bot/stores/nvidia.py", line 313, in run_items
    log.info(fut.result())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/jeremychan/GitHub/nvidia-bot/stores/nvidia.py", line 322, in buy
    while not self.add_to_cart(product_id) and self.enabled:
  File "/Users/jeremychan/GitHub/nvidia-bot/stores/nvidia.py", line 429, in add_to_cart
    DIGITAL_RIVER_ADD_TO_CART_API_URL, headers=DEFAULT_HEADERS, params=params
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
```

**Comment by Hari-Nagarajan** [comment]
This should be fixed by https://github.com/Hari-Nagarajan/nvidia-bot/commit/0f9d24ec583d2a94ea08a46aba958847a69c3f4f#diff-1cf3dba9b1118cb0f8672d0d30f53057

**Comment by jeremych1000** [comment]
Perfect, thanks! Will pull and re-open if it appears again.

**Comment by jeremych1000** [comment]
Reopening as I've just pulled latest master and it's happened again.

Using commit dc034cd52c23bedec28ec0bc9dd39808b337f08d

```
❯ python3 app.py nvidia
? What GPU are you after?  3080
? What locale shall we use?  en_gb
INFO: "2020-09-22 18:53:37,033 - Initializing notification handlers
INFO: "2020-09-22 18:53:37,034 - Enabled Handlers: []
INFO: "2020-09-22 18:53:37,034 - Opening Webdriver
INFO: "2020-09-22 18:53:39,387 - Signing in.
INFO: "2020-09-22 18:53:40,733 - Adding driver cookies to session
INFO: "2020-09-22 18:53:40,733 - Getting product IDs
INFO: "2020-09-22 18:53:41,873 - We have 1 product IDs for NVIDIA GEFORCE RTX 3080
INFO: "2020-09-22 18:53:41,873 - Product IDs: {5438792800}
INFO: "2020-09-22 18:53:41,874 - Checking stock for 5438792800 at 3 second intervals.
Traceback (most recent call last):
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 5, in <module>
    cli.main()
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/jeremychan/GitHub/nvidia-bot/cli/cli.py", line 32, in nvidia
    nv.run_items()
  File "/Users/jeremychan/GitHub/nvidia-bot/stores/nvidia.py", line 323, in run_items
    log.info(fut.result())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/jeremychan/GitHub/nvidia-bot/stores/nvidia.py", line 332, in buy
    while not self.add_to_cart(product_id) and self.enabled:
  File "/Users/jeremychan/GitHub/nvidia-bot/stores/nvidia.py", line 440, in add_to_cart
    DIGITAL_RIVER_ADD_TO_CART_API_URL, headers=DEFAULT_HEADERS, params=params
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Users/jeremychan/GitHub/nvidia-bot/utils/http.py", line 15, in send
    return super().send(request, **kwargs)
  File "/Users/jeremychan/.local/share/virtualenvs/nvidia-bot-1-ZZV8bi/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
```

**Comment by jeremych1000** [comment]
Closing as fixed by https://github.com/Hari-Nagarajan/nvidia-bot/commit/e35914af92d08e0e3f6421b2736c95e0ea94131b
